# Generated by Django 5.1.3 on 2024-12-04 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0004_enrollment_alter_subject_students'),
        ('users', '0004_alter_enrollment_mark'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enrollment',
        ),
    ]
