# Generated by Django 5.1.4 on 2025-01-03 21:23

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0005_alter_subject_teacher'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='mark',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='subject',
            name='students',
            field=models.ManyToManyField(related_name='enrolled', through='subjects.Enrollment', to=settings.AUTH_USER_MODEL),
        ),
    ]
